In [1]:
import os
os.chdir('..')

import equitorch.irreps
from equitorch.irreps import Irrep, Irreps
# from irreps import segments


In [2]:
# print("="*40)
# print("Irrep 类演示")
# print("="*40)

# # 测试不同初始化方式
# ir1 = Irrep(2, 'e')
# ir2 = Irrep("3o")
# ir3 = Irrep(0)
# ir4 = Irrep(1, None)

# print("\n1. 不同初始化方式：")
# print(f"Irrep(2, 'e') -> {ir1}")      # 2e
# print(f"Irrep('3o') -> {ir2}")        # 3o
# print(f"Irrep(0) -> {ir3}")           # 0
# print(f"Irrep(1, None) -> {ir4}")     # 1

# # 测试比较操作
# print("\n2. 比较操作：")
# print(f"{ir1} == '2e'? {ir1 == '2e'}")          # True
# print(f"{ir2} == (3, -1)? {ir2 == (3, -1)}")    # True
# print(f"{ir3} == 0? {ir3 == 0}")                # True

# # 测试维度属性
# print("\n3. 维度计算：")
# print(f"{ir1}.dim = {ir1.dim}")  # 2 * 2+1=5
# print(f"{ir3}.dim = {ir3.dim}")  # 2 * 0+1=1

# print("\n" + "="*40)
# print("Irreps 类演示")
# print("="*40)

# # 测试字符串初始化
# irreps1 = Irreps("4x0+3x1e", channels=2)
# print("\n1. 字符串初始化:")
# print(irreps1)  # Irreps(4x0+1e+1e+1e, channels=2)

# # 测试元组初始化（生成范围）
# irreps2 = Irreps((0, 2), channels=3)
# print("\n2. 范围初始化 (0-2):")
# print(irreps2)  # Irreps(0+1+2, channels=3)

# # 测试列表初始化
# irreps3 = Irreps([0, '1e', (2, -1)], channels=4)
# print("\n3. 列表初始化:")
# print(irreps3)  # Irreps(0+1e+2o, channels=4)

# # 测试等值比较
# print("\n4. 等值比较:")
# print(f"{irreps1} == {irreps2}? {irreps1 == irreps2}")  # False


In [3]:
# irreps1 == ('4x0+3x1e',4)

In [4]:
# Irrep((2, -1))

In [5]:
# Irreps(((0,3),4))

In [6]:
# Irreps((0, 3), 4)

In [7]:
# {ir1:1}

In [8]:
# Irreps("0e+0o+0", 4).sorted()
# Irreps("3x0e+0e").sorted()
# Irreps("0o+3x0o+0e+3x1+3x2e+4x1", 4).simplified()
# Irreps("2e", 2) + Irreps("1o", 2)
# "1e" + Irreps("3x0e") 
# Irreps("1e", 3) * 2
# 3 * Irreps("2o+3e")
# Irreps("2x0e+3x1o", channels=4).flatten()

In [9]:
print(Irreps("6x0 + 1 + 2e + 5x2o"))
print(Irreps((0, 3)) )
print(Irreps([0, "1e", "2o"])  )
print(Irreps("1e")      )

Irreps(6x0+1+2e+5x2o)
Irreps(0+1+2+3)
Irreps(0+1e+2o)
Irreps(1e)


In [10]:
print(Irreps("1x0e") == Irreps("1x0e"))
print(Irreps("1x0e") == Irreps("0e"))
print(Irreps("1x0e") == Irreps("1x0"))
print(Irreps("2x0e+1x0e") == Irreps("3x0e"))
print(Irreps("2x0e+1x0e") == Irreps("1x0e+2x0e"))
print(Irreps("3x1e+2o") == "3x1e + 2o")

True
True
False
False
False
True


In [11]:
print(Irreps("0e+0o+0").sorted())
print(Irreps("3x0e+0e").sorted())
print(Irreps("0o+3x0o+0e+3x1+3x2e+4x1").simplified())

Irreps(0+0e+0o)
Irreps(0e+3x0e)
Irreps(0e+4x0o+7x1+3x2e)


In [12]:
Irreps("2e") + Irreps("1o")

Irreps(2e+1o)

In [13]:
"3e" + Irreps("2e")

Irreps(3e+2e)

In [14]:
Irreps("") + '2e'

Irreps(2e)

In [15]:
print(Irreps("4x0o+4x0e+4x1o+4x1e").eliminate_parity())
print(Irreps("4x0o+4x0e+4x1o+4x1e").eliminate_parity(simplified=True))

Irreps(4x0+4x0+4x1+4x1)
Irreps(8x0+8x1)


In [16]:
print(Irrep("1e") * Irrep("1o"))
print(Irrep("2e") * Irrep("1e"))
print(Irrep("0o") * Irrep("0o"))
print(Irrep("3e") * Irrep("0"))
print(Irrep("1") * Irrep("3o"))

Irreps(0o+1o+2o)
Irreps(1e+2e+3e)
Irreps(0e)
Irreps(3)
Irreps(2+3+4)


In [17]:
print(Irreps("1x0e + 1x1o") * Irreps("1x0o + 1x1e"))

Irreps(2x0+5x1)


In [18]:
Irreps("2x0e + 3x1o") * Irreps("1x1e + 2x2o")

Irreps(0+4x1+7x2+7x3+4x4+3x5+3x6)

In [19]:
Irreps("2x0e + 3x1o") * Irreps("1x1e + 2x2o")

Irreps(0+4x1+7x2+7x3+4x4+3x5+3x6)

In [20]:
Irreps("1o") * Irreps("1o") * Irreps("1o") * Irreps("1")

Irreps(0+4x1+5x2+6x3)

In [21]:
print(Irreps("2x0e + 3x1o").dim)

11


In [22]:
print(list(Irreps("2x0+2x0e+3x1o+2")))
print(list(Irreps("2x0+2x0e+3x1o+2").dims()))

[0, 0, 0e, 0e, 1o, 1o, 1o, 2]
[1, 1, 1, 1, 3, 3, 3, 5]


In [23]:
Irreps("").isomorphic_to((3,1))

True

In [24]:
from irreps import irrep_segments
print(irrep_segments(Irreps("1o")))
print(irrep_segments(Irreps((0,4))))
print(irrep_segments("0+2x1e+3x2e+4"))

tensor([0, 3])
tensor([ 0,  1,  4,  9, 16, 25])
tensor([ 0,  1,  4,  7, 12, 17, 22, 31])


In [27]:
from irreps import irrep_indices
print(irrep_indices(Irreps("1o")))
print(irrep_indices(Irreps((0,3))))
print(irrep_indices("0+2x1e+2e"))




tensor([0, 0, 0])
tensor([0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3])
tensor([0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3])


In [3]:
irreps = Irreps("2x0e + 1x1o + 2x2")

In [6]:
print(irreps[0])
print(irreps[2])
print(irreps[1:4])
print(irreps[:2])
print(irreps[3:])
print(irreps[::2])

0e
1o
Irreps(0e+1o+2)
Irreps(0e+0e)
Irreps(2+2)


ValueError: Irreps slicing only supports a step of 1

In [10]:
from equitorch.irreps import Irrep, Irreps, has_path

def full_product_irreps_paths(irreps_in1: Irreps, irreps_in2: Irreps, irreps_out: Irreps = None):
    r"""
    Compute the coupling paths between two input irreps sets to produce an output irreps set.

    This function calculates all valid coupling paths from the tensor product of ``irreps_in1``
    and ``irreps_in2`` to ``irreps_out``. When ``irreps_out`` is not specified, it automatically
    generates all possible irreps from the tensor product.

    Parameters
    ----------
    irreps_in1 : Irreps
        First input set of irreducible representations
    irreps_in2 : Irreps
        Second input set of irreducible representations
    irreps_out : Irreps, optional
        Target output irreps. If None, uses all possible outputs from the tensor product.

    Returns
    -------
    Tuple[Irreps, List[Tuple[int, int, int]]]
        A tuple containing:
        - Coupled irreps (with multiplicities indicating available paths)
        - List of coupling paths as (path_id, input1_idx, input2_idx) tuples

    Examples
    --------
    >>> irreps1 = Irreps("1e")
    >>> irreps2 = Irreps("1o")
    >>> product, paths = full_product_irreps_paths(irreps1, irreps2)
    >>> print(product)
    Irreps(0o+1o+2o)
    >>> print(paths)
    [(0, 0, 0), (1, 0, 0), (2, 0, 0)]

    >>> out = Irreps("0o+2o")
    >>> product, paths = full_product_irreps_paths(irreps1, irreps2, out)
    >>> print(product)
    Irreps(0o+2o)
    >>> print(paths)
    [(0, 0, 0), (1, 0, 0)]

    >>> irreps1 = Irreps("2x0e")
    >>> irreps2 = Irreps("3x1o")
    >>> product, paths = full_product_irreps_paths(irreps1, irreps2)
    >>> product
    Irreps(3x1o+3x2o)
    >>> paths
    """
    if irreps_out is None:
        irreps_out = Irreps(list({ir for ir1 in irreps_in1 for ir2 in irreps_in2 for ir in ir1 * ir2}))
    else:
        irreps_out = Irreps(list({ir for ir in irreps_out}))
    coupled_irreps = []
    paths = []
    
    # Iterate through all possible output irreps
    for ir_idx_out, ir_out in enumerate(irreps_out):
        mul_out = 0
        # Iterate through all possible input1 irreps
        for ir_idx_in1, ir_in1 in enumerate(irreps_in1):
            # Iterate through all possible input2 irreps
            for ir_idx_in2, ir_in2 in enumerate(irreps_in2):
                # Check if this input pair can couple to the output irrep
                if has_path(ir_out, ir_in1, ir_in2):
                    mul_out += 1
                    paths.append((len(paths), ir_idx_in1, ir_idx_in2))
        if mul_out > 0:
            coupled_irreps.append((ir_out, mul_out))
    # Create the Irreps object from the collected coupled irreps
    # Each irrep has multiplicity 1 in this intermediate representation
    # coupled_irreps = Irreps("+".join(f'{mul}x{ir}' for ir, mul in coupled_irreps))
    coupled_irreps = Irreps([(ir, mul) for ir, mul in coupled_irreps])
    
    # Sort the coupled irreps for consistency
    coupled_irreps = coupled_irreps.sorted()
    
    return coupled_irreps, paths

In [11]:
irreps1 = Irreps("1e")
irreps2 = Irreps("1o")
product, paths = full_product_irreps_paths(irreps1, irreps2)
print(product)
print(paths)


Irreps(0o+1o+2o)
[(0, 0, 0), (1, 0, 0), (2, 0, 0)]


In [16]:
out = Irreps("0o+2o")
product, paths = full_product_irreps_paths(irreps1, irreps2, out)
print(product)

Irreps(2o)


In [13]:
irreps1 = Irreps("0e + 1o + 2")  # O(3)偶 + O(3)奇 + SO(3)
irreps2 = Irreps("1 + 2o")       # SO(3) + O(3)奇

In [17]:
irreps1 = Irreps("0e + 1o + 2")  # O(3)偶 + O(3)奇 + SO(3)
irreps2 = Irreps("1 + 2o")       # SO(3) + O(3)奇
product, paths = full_product_irreps_paths(irreps1, irreps2)
print(product)

Irreps(2x0+5x1+1e+5x2+2e+2o+3x3+3e+4)


In [15]:
print(product)
print(len(product))

Irreps(2x0+5x1+1e+5x2+2e+2o+3x3+3e+4)
20


In [9]:
print(len(paths))

20


In [1]:
from equitorch.irreps import Irreps

In [3]:
Irreps("0e + 0e + 1o + 2e + 2e + 2e").merged()

Irreps(2x0e+1o+3x2e)

In [4]:
Irreps("0+0e+1o+0e+0e").merged()  

Irreps(0+0e+1o+2x0e)

In [ ]:
irreps_uniqued, unique_mapping = equitorch.irreps.unique_irreps(Irreps("0+0e+1o+0e+0e"))
print(irreps_uniqued)
print(unique_mapping)

Irreps(0+0e+1o)
{0: [0], 0e: [1, 3, 4], 1o: [2]}


In [ ]:
irreps_uniqued, unique_mapping = equitorch.irreps.unique_irreps(Irreps("0+0e+1o+0e+0e"))
print(irreps_uniqued)
print(unique_mapping)

Irreps(0+0e+1o)
{0: [0], 0e: [1, 3, 4], 1o: [2]}


In [ ]:
irreps_uniqued, unique_mapping = equitorch.irreps.unique_irreps(Irreps("0+0e+1o+0e+0e"))
print(irreps_uniqued)
print(unique_mapping)

Irreps(0+0e+1o)
{0: [0], 0e: [1, 3, 4], 1o: [2]}


In [ ]:
irreps_uniqued, unique_mapping = equitorch.irreps.unique_irreps(Irreps("0+0e+1o+0e+0e"))
print(irreps_uniqued)
print(unique_mapping)

Irreps(0+0e+1o)
{0: [0], 0e: [1, 3, 4], 1o: [2]}


In [3]:
Irrep('2e') in (Irreps("0+0e+1o+0e+0e")  * Irreps("0+0e+1o+0e+0e"))

True

In [2]:
Irreps("0+0e+1o+0e+0e")  * Irreps("0+0e+1o+0e+0e")

Irreps(7x0+10x0e+2x1+1e+6x1o+2e)